### ISSUE TITLE
Does it support ass or smi format?

### ISSUE THREAD

**Issue by larrytin** [shinyieva/SOSubtitle#2]

**Comment by shinyieva** [comment]
For now, only support .SRT format.

**Comment by larrytin** [comment]
Do you know any other open-source libraries that support render ass on ios?

**Comment by shinyieva** [comment]
No, sorry, I don´t know about it. If you want, you can add this format to the library.

**Comment by larrytin** [comment]
Thanks for the lightning fast reply.
